{% set name = "flake8-rst" %}
{% set version = "0.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f447520288a73bce2eb9ce09efdd10cebf381468200e7ee1b9ac7b6e0d30bd6f

build:
  number: 0
  noarch: python
  entry_points:
    - flake8-rst = flake8_rst.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - flake8 >=3.5.0
    - pip
    - python
  run:
    - flake8 >=3.5.0
    - python

test:
  imports:
    - flake8_rst
  commands:
    - flake8-rst --help

about:
  home: https://github.com/kataev/flake8-rst
  license: MIT
  license_family: MIT
   # LICENSE File currently missing from sdist. ref [PR 1](https://github.com/kataev/flake8-rst/pull/1)
  license_file: LICENSE
  summary: flake8 for code in rst files and docstrings
  doc_url: https://github.com/kataev/flake8-rst
  dev_url: https://github.com/kataev/flake8-rst

extra:
  recipe-maintainers:
    - FHaase
