travis:
  secure:
    BINSTAR_TOKEN: MySf0yJHQJ5i079poHI+Cg+I4rx/A4kJqnZ62oG7q3gCjfeiYeDOSPSgD1WjnKZ5uUXf0FyVlDl9tA6FjczLdnBF7AU55+kVbxjQSS5Ps3/lpM8HLI98IKXy+mCNoVfnkrXsn6w6j+zhMK8OAn+peynqh92Pax/sM8ODeYfRUrBllYG1XJsHOzqsKGGpHuxuaCA9GaB+1+2nXY4fRAWhkSRzmC988oKb99zkl7G3wKsUFauneyWXdSuJQVhVp/4BLaNx/8s51FCMaLXImXke11wxTMpa4D0nyvtniHFKU3QdZ+Cb1jd3kEVjfgkN6hGd2TG6VBvI5TISB02wk5eEITL+hfwR2NnGFNO2dM1UiNkkYtYPkheN+Wd1zqh9rzAg1k/MMP9Yrc+AjT4kP5C8pqvfX6IfoBTJ6kOz4if3J+VGQmq5LXl8BzwbTvgfGUCFY10NZn+mTlNQ4BCICzPINt2LO9huV3teF2p6SEDnaOR+k0tXOPaogOTu5O9PuECGHcASWRLhBFmDDaxskes+WGkZ/j8pLJPUp4x9Y3oELiNTJBC1GdhEIHm8HA/fL9uV3gI2oZJGzqsUFQjdnDprgxRIo798shlSaMwdTN/x93kz48BiZAh6Ugh5c8aGmzkuyS3qpSP7wCtM5jLvHzwR6DyuqHtNzidisVBO83U3gIk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
